//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antix.Html {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class HtmlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HtmlSettings defaultInstance = ((HtmlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HtmlSettings())));
        
        public static HtmlSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"")]
        public string HtmlAttributeQuote {
            get {
                return ((string)(this["HtmlAttributeQuote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("area,audio,base,basefont,br,col,command,embed,frame,hr,img,input,isindex,keygen,l" +
            "ink,meta,param,source,track,video,wbr")]
        public string HtmlNonContainers {
            get {
                return ((string)(this["HtmlNonContainers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a,em,strong,q,cite,dfn,i,b,sup,sub,small,code,mark,del,s,ins,abbr,span,br")]
        public string HtmlInlineElements {
            get {
                return ((string)(this["HtmlInlineElements"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("script,style")]
        public string HtmlTextOnlyContainers {
            get {
                return ((string)(this["HtmlTextOnlyContainers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!doctype,!--|--")]
        public string HtmlDeclarations {
            get {
                return ((string)(this["HtmlDeclarations"]));
            }
        }
    }
}
